version: 0.2

env:
  variables:
    # 定义Android构建相关环境变量
    ANDROID_COMPILE_SDK: "36"
    ANDROID_BUILD_TOOLS: "36.0.0"
    # 新增：cmdline-tools版本
    CMDLINE_TOOLS_VERSION: "7583922"
    # 新增：Android SDK安装根目录
    ANDROID_HOME: "/usr/local/android-sdk"
  # 使用AWS Secrets Manager存储签名信息
  secrets-manager:
    KEYSTORE_PASSWORD: "arn:aws:secretsmanager:us-east-1:123456789012:secret:android-keystore:keystore_password"
    KEY_ALIAS: "arn:aws:secretsmanager:us-east-1:123456789012:secret:android-keystore:key_alias"
    KEY_PASSWORD: "arn:aws:secretsmanager:us-east-1:123456789012:secret:android-keystore:key_password"
    KEYSTORE_BASE64: "arn:aws:secretsmanager:us-east-1:123456789012:secret:android-keystore:keystore_base64"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      # 1. Amazon Linux 使用 yum，但很多工具已预装
      - yum install -y unzip || echo "unzip may already be installed"
      # 2. 确保Gradle可执行
      - chmod +x ./gradlew
      # 3. 下载并安装cmdline-tools（包含sdkmanager）
      - mkdir -p $ANDROID_HOME/cmdline-tools/latest
      - curl -fsSL "https://dl.google.com/android/repository/commandlinetools-linux-${CMDLINE_TOOLS_VERSION}_latest.zip" -o cmdline-tools.zip
      - unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
      - mv $ANDROID_HOME/cmdline-tools/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
      - rm -f cmdline-tools.zip
      # 4. 配置环境变量并安装SDK组件
      - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      - $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-$ANDROID_COMPILE_SDK" "build-tools;$ANDROID_BUILD_TOOLS" --sdk_root=$ANDROID_HOME
      # 5. 自动接受所有SDK许可证
      - yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$ANDROID_HOME

  pre_build:
    commands:
      # 生成local.properties，告诉Gradle SDK路径
      - echo "sdk.dir=$ANDROID_HOME" > local.properties
      # 从Secrets Manager恢复keystore文件
      - echo $KEYSTORE_BASE64 | base64 -d > release.keystore
      - chmod 600 release.keystore
      - ./gradlew dependencies --no-daemon

  build:
    commands:
      # 1. 先运行单元测试
      - ./gradlew testDebugUnitTest --no-daemon
      # 2. 运行静态代码分析
      - ./gradlew lintDebug --no-daemon
      # 3. 生成Debug APK
      - ./gradlew assembleDebug --no-daemon
      # 4. 生成签名的Release APK
      - ./gradlew assembleRelease --no-daemon -Pandroid.injected.signing.store.file=./release.keystore -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD -Pandroid.injected.signing.key.alias=$KEY_ALIAS -Pandroid.injected.signing.key.password=$KEY_PASSWORD

  post_build:
    commands:
      - echo "Build completed successfully"
      # 清理敏感文件
      - rm -f release.keystore

artifacts:
  files:
    - app/build/outputs/apk/debug/*.apk
    - app/build/outputs/apk/release/*.apk
    - app/build/reports/tests/testDebugUnitTest/**/*
    - app/build/reports/lint-results-debug.html
    - app/build/reports/lint-results-debug.xml
  discard-paths: no

cache:
  paths:
    - ~/.gradle/caches/**/*
    - ~/.gradle/wrapper/**/*
    - app/build/cache/**/*
    # 缓存SDK组件，加速后续构建
    - $ANDROID_HOME/platforms/**/*
    - $ANDROID_HOME/build-tools/**/*